# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = ../../../gcc-13.2.0/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
